#!/bin/sh
#
# Print public IP if this host (with or without TOR)

if [ "$1" = "tor" ]; then
  useTor=1
else 
  useTor=0
fi

showIpUrl="http://www.fastweb.it/myfastpage/assistenza/guide-fisso/servizi/visualizza-indirizzo-ip/"
tor="localhost:9050"

if [ "$useTor" = "1" ]; then
  curl -s $showIpUrl | grep '<div class="text2">' | sed -e 's/<div class="text2">//' | sed -e 's/<\/div>//'
else
  curl -s --socks5-hostname $tor $showIpUrl | grep '<div class="text2">' | sed -e 's/<div class="text2">//' | sed -e 's/<\/div>//'
fi