<?php
  $this->sitesDefinitions = [
    "facebook" => [
      "url" => "http://www.facebook.com",
      "path" => "/persons",
      "charset" => "utf-8",
      "accepts-tor" => true,
      "patterns" => [
        "ban-text" => "/TODO/s",
        "person" => "/TODO/s",
        "person-id" => "/TODO/s",
        "person-details-url" => "/TODO/s",
        "person-img-url" => "/TODO/s",
        "person-name" => "/TODO/s",
        "person-sex" => "/TODO/s",
        "person-zone" => "/TODO/s",
        "person-description" => "/TODO/s",
        "person-phone" => "/TODO/s",
        "person-phone-vacation" => "/TODO/s",
        "person-phone-unavailable" => "/TODO/s",
        "person-nationality" => "/TODO/s",
        "person-photo" => "/TODO/s",
      ],
    ],
    "twitter" => [
      "url" => "http://www.twitter.com",
      "charset" => "utf-8",
      "path" => "/people",
      "accepts-tor" => true,
      "patterns" => [
        "ban-text" => "/TODO/s",
        "person" => "/TODO/s",
        "person-id" => "/TODO/s",
        "person-details-url" => "/TODO/s",
        "person-img-url" => "/TODO/s",
        "person-name" => "/TODO/s",
        "person-sex" => "/TODO/s",
        "person-zone" => "/TODO/s",
        "person-description" => "/TODO/s",
        "person-phone" => "/TODO/s",
        "person-phone-vacation" => "/TODO/s",
        "person-phone-unavailable" => "/TODO/s",
        "person-nationality" => "/TODO/s",
        "person-photo" => "/TODO/s",
      ],
    ],
?>