#!/bin/bash
#
# Run project development tools:
#  - run tail of apache error log
#  - run tail of slim log
#  - run database browser
#  - run grunt server

gnome-terminal --geometry=150x12+200+500 -x sh -c "tail -f /var/log/apache2/error.log"
gnome-terminal --geometry=150x12+240+280 -x sh -c "tail -f /var/www/html/escrape/api/logs/*-*-*.log"
sqlitebrowser "/var/www/html/escrape/api/db/escrape.sqlite" &
grunt serve
