#!/bin/bash
#
# Erase dababase (DB + photos) and re-sync it

clear
#echo "erasing database..."
#sudo rm -rf /var/www/html/escrape/api/db/*
echo "re-syncing persons..."
time curl -X GET -i localhost/escrape/api/persons/sync && echo