#!/bin/bash
#
# Erase dababase (DB + photos) and resync it

xdebug="--cookie 'XDEBUG_SESSION=sublime.xdebug'"

usage() {
  echo "\
Usage: $0  [ OPTIONS ]  MODE

           MODE:
             [ all       (resync anything)      ] |
             [ persons   (resync only persons)  ] |
             [ comments  (resync only comments) ]

           OPTIONS:
             [ -d | --drop            (any mode; drop db and resync) ]                                      |
             [ -i | --images-forced   (persons mode only; force resync of all persons images) ]             |
             [ -a | --inactive-forced (comments mode only; force resync of comments for inactive persons) ]
" 1>&2
  exit 1
}

while getopts ":dia" o; do
  case "${o}" in
    d)
      drop=1
      ;;
    i)
      images=1
      ;;
    a)
      inactivetoo=1
      ;;
    *)
      usage
      ;;
  esac
done
what=${@:$OPTIND:1}

clear
if [[ $what =~ ^all$ ]]; then
  :
else
  if [[ $what =~ ^persons$ ]]; then
    :
  else
    if [[ $what =~ ^comments$ ]]; then
      :
    else
      usage
    fi
  fi
fi

if [ -n "$drop" ]; then
  read -p "Are you sure to erase the whole database and photos [y/N]? " -n 1 -r
  if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "dropping database..."
    db_backup_path="/var/www/html/escrape/api/db-backup/`date +%Y-%m-%d_%H:%M:%S`"
    mkdir -p "$db_backup_path"
    mv /var/www/html/escrape/api/db/* "$db_backup_path"
  fi
fi

if [[ $what =~ ^all$ || $what =~ ^persons$ ]]; then
  if [ -n "$images" ]; then
    echo "resyncing persons (resync of all images forced)"
    time curl $xdebug -X GET -i localhost/escrape/api/persons/sync/full
  else
    echo "resyncing persons"
    time curl $xdebug -X GET -i localhost/escrape/api/persons/sync
  fi
fi
if [[ $what =~ ^all$ || $what =~ ^comments$ ]]; then
  if [ -n "$inactivetoo" ]; then
    echo "resyncing comments (resync of all persons comments forced)"
    # TODO: passing 'all' to comments/sync ...
    time curl $xdebug -X GET -i localhost/escrape/api/comments/sync
  else
    echo "resyncing comments"
    time curl $xdebug -X GET -i localhost/escrape/api/comments/sync
  fi
fi
echo
