#!/bin/bash
#
# Erase dababase (DB + photos) and re-sync it

usage() {
  echo "
Usage: $0
          [ -d | --drop (drop db and re-sync) ] |
          [ -i | --images(sync all images too) ]
" 1>&2
  exit 1
}

while getopts ":di" o; do
  case "${o}" in
    d)
      drop=1
      ;;
    i)
      #i=${OPTARG}
      images=1
      ;;
    *)
      usage
      ;;
  esac
done
shift $((OPTIND-1))

clear
if [ -n "$drop" ]; then
  echo "dropping database..."
  # TODO: backup db! (and photos...)
  sudo rm -rf /var/www/html/escrape/api/db/*
fi
if [ -n "$images" ]; then
  echo "re-syncing persons (all images included, full mode)..."
  time curl -X GET -i localhost/escrape/api/persons/sync/full && echo
else
  echo "re-syncing persons (ignore old images, standard mode)..."
  time curl -X GET -i localhost/escrape/api/persons/sync && echo
fi