<?php
  $this->sitesDefinitions = [
    "linkedin" => [
      "url" => "http://www.linkedin.com",
      "path" => "/",
      "charset" => "utf-8",
      "patterns" => [
        "security-check" => "/TODO SECURITY_CHECK/s",
        "person" => "/TODO PERSON/s",
        "person-id" => "/TODO PERSON_ID/s",
        "person-details-url" => "/TODO PERSON DETAILS_UURL/s",
        "person-img-url" => "/TODO PERSON IMG_URL/s",
        "person-name" => "/TODO PERSON /s",
        "person-sex" => "/TODO PERSON /s",
        "person-zone" => "/TODO PERSON /s",
        "person-description" => "/TODO PERSON /s",
        "person-phone" => "/TODO PERSON /s",
        "person-phone-vacation" => "/TODO PERSON_VACATION/s",
        "person-phone-unavailable" => "/TODO PERSON_UNAVAILABLE/s",
        "person-nationality" => "/TODO PERSON_NATIONALITY/s",
        "person-photo" => "/TODO PERSON_PHOTO/s",
      ],
    ],
    "facebook" => [
      "url" => "http://www.facebook.com",
      "path" => "/",
      "charset" => "utf-8",
      "patterns" => [
        "security-check" => "/TODO SECURITY_CHECK/s",
        "person" => "/TODO PERSON/s",
        "person-id" => "/TODO PERSON_ID/s",
        "person-details-url" => "/TODO PERSON DETAILS_UURL/s",
        "person-img-url" => "/TODO PERSON IMG_URL/s",
        "person-name" => "/TODO PERSON /s",
        "person-sex" => "/TODO PERSON /s",
        "person-zone" => "/TODO PERSON /s",
        "person-description" => "/TODO PERSON /s",
        "person-phone" => "/TODO PERSON /s",
        "person-phone-vacation" => "/TODO PERSON_VACATION/s",
        "person-phone-unavailable" => "/TODO PERSON_UNAVAILABLE/s",
        "person-nationality" => "/TODO PERSON_NATIONALITY/s",
        "person-photo" => "/TODO PERSON_PHOTO/s",
      ],
    ],
  ];
?>